apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: harbor.scs.buaa.edu.cn/bugit-test/nginx:1.17
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "800Mi"
              cpu: "1"
            requests:
              memory: "600Mi"
              cpu: "1"
      imagePullSecrets:
        - name: bugit-test
